export const ADD_ACCOUNT_FORM_CONFIG = {
  title: null,
  sections: [
    {
      title: null,
      fields: [
        {
          name: 'accountHolderName',
          label: 'Account Holder Name',
          type: 'text',
          placeholder: 'Enter Account Holder Name',
          required: true,
          width: 'half',
        },
        {
          name: 'businessName',
          label: 'Business Name',
          type: 'text',
          placeholder: 'Enter Business Name',
          required: true,
          width: 'half',
        },
        {
          name: 'bankName',
          label: 'Bank Name',
          type: 'text',
          placeholder: 'Enter Bank Name',
          required: true,
          width: 'half',
        },
        {
          name: 'nationality',
          label: 'Nationality',
          type: 'dropdown',
          placeholder: 'Select Nationality',
          options: ['British', 'American', 'Canadian', 'Australian', 'Indian', 'Other'],
          required: true,
          width: 'half',
        },
        {
          name: 'maritalStatus',
          label: 'Marital Status',
          type: 'dropdown',
          placeholder: 'Select Marital Status',
          options: ['Married', 'Single', 'Divorced', 'Widowed', 'Other'],
          required: true,
          width: 'half',
        },
        {
          name: 'dependents',
          label: 'Dependents',
          type: 'number',
          placeholder: 'Enter Number of Dependents',
          required: true,
          width: 'half',
        },
      ],
    },
    {
      title: 'Residential Address',
      fields: [
        {
          name: 'postalCode',
          label: 'Postal Code',
          type: 'text',
          placeholder: 'Enter Postal Code',
          required: true,
          width: 'half',
        },
        {
          name: 'selectedAddress',
          label: 'Select Your Address',
          type: 'dropdown',
          placeholder: 'Select Your Address',
          options: [],
          required: true,
          width: 'half',
          isAddressLookup: true,
        },
        {
          name: 'contact',
          label: 'Contact',
          type: 'text',
          placeholder: 'Enter Contact Name',
          required: true,
          width: 'half',
        },
        {
          name: 'houseNumberStreet',
          label: 'House number and Street',
          type: 'text',
          placeholder: 'Enter House number and Street',
          required: true,
          width: 'half',
        },
        {
          name: 'locality',
          label: 'Locality (Post Town)',
          type: 'text',
          placeholder: 'Enter Locality/Post Town',
          required: true,
          width: 'half',
        },
        {
          name: 'country',
          label: 'Country',
          type: 'dropdown',
          placeholder: 'Select Country',
          options: ['United Kingdom'],
          required: true,
          width: 'half',
        },
        {
          name: 'residentialStatus',
          label: 'Residential Status',
          type: 'dropdown',
          placeholder: 'Select Residential Status',
          options: ['Renting', 'Owned', 'Living with Family', 'Other'],
          required: true,
          width: 'half',
        },
        {
          name: 'yearsAtAddress',
          label: 'Years at Current Address',
          type: 'number',
          placeholder: 'Enter Years',
          required: true,
          width: 'half',
        },
      ],
    },
  ],
};
