export const loanFormConfig = [
  {
    sectionTitle: '1. Applicant Details',
    fields: [
      {
        name: 'firstName',
        label: 'First Name',
        type: 'text',
        placeholder: 'Enter first name',
        required: true,
        width: 'half',
      },
      {
        name: 'lastName',
        label: 'Last Name',
        type: 'text',
        placeholder: 'Enter last name',
        required: true,
        width: 'half',
      },
      {
        name: 'dateOfBirth',
        label: 'Date of Birth',
        type: 'date',
        placeholder: 'Select Date',
        required: true,
        width: 'half',
      },
      {
        name: 'nationality',
        label: 'Nationality',
        type: 'text',
        placeholder: 'Enter nationality',
        required: true,
        width: 'half',
      },
      {
        name: 'maritalStatus',
        label: 'Marital Status',
        type: 'dropdown',
        placeholder: 'Select status',
        options: ['Single', 'Married', 'Divorced', 'Widowed'],
        required: true,
        width: 'half',
      },
      {
        name: 'dependents',
        label: 'Dependents',
        type: 'dropdown',
        placeholder: 'Select number',
        options: ['0', '1', '2', '3', '4+'],
        required: true,
        width: 'half',
      },
    ],
  },
  {
    sectionTitle: 'Residential Address',
    fields: [
      {
        name: 'postalCode',
        label: 'Postal Code',
        type: 'addressLookup',
        placeholder: 'Enter postal code',
        required: true,
        width: 'half',
      },
      {
        name: 'selectedAddress',
        label: 'Select Your Address',
        type: 'text',
        placeholder: 'Address will appear here',
        required: true,
        width: 'half',
        readOnly: true,
      },
      {
        name: 'contact',
        label: 'Contact',
        type: 'number',
        placeholder: 'Enter contact number',
        required: true,
        width: 'half',
      },
      {
        name: 'houseStreet',
        label: 'House number and Street',
        type: 'text',
        placeholder: 'Enter house number and street',
        required: true,
        width: 'half',
      },
      {
        name: 'locality',
        label: 'Locality (Post Town)',
        type: 'text',
        placeholder: 'Enter locality',
        required: true,
        width: 'half',
      },
      {
        name: 'country',
        label: 'Country',
        type: 'text',
        placeholder: 'Enter country',
        required: true,
        width: 'half',
      },
      {
        name: 'residentialStatus',
        label: 'Residential Status',
        type: 'dropdown',
        placeholder: 'Select status',
        options: ['Homeowner', 'Renting', 'Living with Parents', 'Other'],
        required: true,
        width: 'half',
      },
      {
        name: 'yearsAtAddress',
        label: 'Years at Current Address',
        type: 'text',
        placeholder: 'Enter years',
        required: true,
        width: 'half',
      },
    ],
  },
  {
    sectionTitle: '3. Finance Request Details',
    fields: [
      {
        name: 'financeType',
        label: 'Finance Type',
        type: 'dropdown',
        placeholder: 'Select finance type',
        options: ['Home Purchase Plan (Murabaha)', 'Buy to Let', 'Refinance'],
        required: true,
        width: 'half',
      },
      {
        name: 'propertyValue',
        label: 'Property Value',
        type: 'number',
        placeholder: '£0.00',
        required: true,
        width: 'half',
      },
      {
        name: 'requestedAmount',
        label: 'Requested Finance Amount',
        type: 'number',
        placeholder: '£0.00',
        required: true,
        width: 'half',
      },
      {
        name: 'depositPaid',
        label: 'Deposit Paid',
        type: 'number',
        placeholder: '£0.00',
        required: true,
        width: 'half',
      },
      {
        name: 'tenure',
        label: 'Tenure Selected',
        type: 'dropdown',
        placeholder: 'Select tenure',
        options: ['12 Months', '24 Months', '36 Months', '48 Months', '60 Months', '120 Months'],
        required: true,
        width: 'half',
      },
      {
        name: 'purposeOfFinance',
        label: 'Purpose of Finance',
        type: 'dropdown',
        placeholder: 'Select purpose',
        options: ['Residential Property Purchase', 'Investment', 'Other'],
        required: true,
        width: 'half',
      },
      {
        name: 'installmentDate',
        label: 'Preferred Monthly Instalment Date',
        type: 'dropdown',
        placeholder: 'Select date',
        options: [
          '1st of Every Month',
          '5th of Every Month',
          '15th of Every Month',
          '25th of Every Month',
        ],
        required: true,
        width: 'half',
      },
    ],
  },
  {
    sectionTitle: 'Your Financial Commitments',
    fields: [
      {
        name: 'monthlyExpenses',
        label: 'Your Monthly Expenses',
        type: 'number',
        placeholder: '£0.00',
        required: false,
        width: 'half',
      },
      {
        name: 'repaymentAmount',
        label: 'Your preferred Repayment Amount',
        type: 'number',
        placeholder: '£0.00',
        required: false,
        width: 'half',
      },
    ],
  },
];
