export const loanFormConfig = [
  {
    sectionTitle: '1. Applicant Details',
    groups: [
      {
        title: null,
        fields: [
          {
            name: 'firstName',
            label: 'First Name',
            type: 'text',
            placeholder: 'Enter first name',
            required: true,
            width: 'half',
          },
          {
            name: 'lastName',
            label: 'Last Name',
            type: 'text',
            placeholder: 'Enter last name',
            required: true,
            width: 'half',
          },
          {
            name: 'dateOfBirth',
            label: 'Date of Birth',
            type: 'date',
            placeholder: 'Select Date',
            required: true,
            width: 'half',
          },
          {
            name: 'nationality',
            label: 'Nationality',
            type: 'text',
            placeholder: 'Enter nationality',
            required: true,
            width: 'half',
          },
          {
            name: 'maritalStatus',
            label: 'Marital Status',
            type: 'dropdown',
            placeholder: 'Select status',
            options: ['Single', 'Married', 'Divorced', 'Widowed'],
            required: true,
            width: 'half',
          },
          {
            name: 'dependents',
            label: 'Dependents',
            type: 'dropdown',
            placeholder: 'Select number',
            options: ['0', '1', '2', '3', '4+'],
            required: true,
            width: 'half',
          },
        ],
      },
      {
        title: 'Residential Address',
        fields: [
          {
            name: 'postalCode',
            label: 'Postal Code',
            type: 'addressLookup',
            placeholder: 'Enter postal code',
            required: true,
            width: 'half',
          },
          {
            name: 'selectedAddress',
            label: 'Select Your Address',
            type: 'text',
            placeholder: 'Address will appear here',
            required: true,
            width: 'half',
            readOnly: true,
          },
          {
            name: 'contact',
            label: 'Contact',
            type: 'text',
            placeholder: 'Enter contact',
            required: true,
            width: 'half',
          },
          {
            name: 'houseStreet',
            label: 'House number and Street',
            type: 'text',
            placeholder: 'Enter house number and street',
            required: true,
            width: 'half',
          },
          {
            name: 'locality',
            label: 'Locality (Post Town)',
            type: 'text',
            placeholder: 'Enter locality',
            required: true,
            width: 'half',
          },
          {
            name: 'country',
            label: 'Country',
            type: 'text',
            placeholder: 'Enter country',
            required: true,
            width: 'half',
          },
          {
            name: 'residentialStatus',
            label: 'Residential Status',
            type: 'dropdown',
            placeholder: 'Select status',
            options: ['Homeowner', 'Renting', 'Living with Parents', 'Other'],
            required: true,
            width: 'half',
          },
          {
            name: 'yearsAtAddress',
            label: 'Years at Current Address',
            type: 'text',
            placeholder: 'Enter years',
            required: true,
            width: 'half',
          },
        ],
      },
    ],
  },
  {
    sectionTitle: '2. Employment & Income Details',
    groups: [
      {
        title: null,
        fields: [
          {
            name: 'employmentStatus',
            label: 'Employment Status',
            type: 'dropdown',
            placeholder: 'Select employment status',
            options: [
              'Full-time',
              'Part-time',
              'Self-employed',
              'Unemployed',
              'Student',
              'Retired',
            ],
            required: true,
            width: 'half',
          },
          {
            name: 'employerName',
            label: 'Employer Name',
            type: 'text',
            placeholder: 'Enter employer name',
            required: true,
            width: 'half',
          },
          {
            name: 'jobTitle',
            label: 'Job Title',
            type: 'text',
            placeholder: 'Enter job title',
            required: true,
            width: 'half',
          },
          {
            name: 'employmentDuration',
            label: 'Employment Duration',
            type: 'text',
            placeholder: 'Enter duration (e.g., 2 years)',
            required: true,
            width: 'half',
          },
          {
            name: 'monthlyGrossIncome',
            label: 'Monthly Gross Income',
            type: 'text',
            placeholder: '£0.00',
            required: true,
            width: 'half',
          },
          {
            name: 'monthlyNetIncome',
            label: 'Monthly Net Income',
            type: 'text',
            placeholder: '£0.00',
            required: true,
            width: 'half',
          },
          {
            name: 'additionalIncome',
            label: 'Additional Income (If any)',
            type: 'dropdown',
            placeholder: 'Select additional income',
            options: ['None', 'Rental Income', 'Business Income', 'Freelance', 'Other'],
            required: true,
            width: 'half',
          },
          {
            name: 'totalMonthlyIncome',
            label: 'Total Monthly Income',
            type: 'text',
            placeholder: '£0.00',
            required: true,
            width: 'half',
            readOnly: false,
          },
        ],
      },
    ],
  },
  {
    sectionTitle: '3. Finance Request Details',
    groups: [
      {
        title: null,
        fields: [
          {
            name: 'financeType',
            label: 'Finance Type',
            type: 'dropdown',
            placeholder: 'Select finance type',
            options: [
              'Home Purchase Plan (Murabaha)',
              'Home Purchase Plan (Ijara)',
              'Refinance',
              'Equity Release',
              'Other',
            ],
            required: true,
            width: 'half',
          },
          {
            name: 'propertyValue',
            label: 'Property Value',
            type: 'text',
            placeholder: '£0.00',
            required: true,
            width: 'half',
          },
          {
            name: 'requestedFinanceAmount',
            label: 'Requested Finance Amount',
            type: 'text',
            placeholder: '£0.00',
            required: true,
            width: 'half',
          },
          {
            name: 'depositPaid',
            label: 'Deposit Paid',
            type: 'text',
            placeholder: '£0.00',
            required: true,
            width: 'half',
          },
          {
            name: 'tenureSelected',
            label: 'Tenure Selected',
            type: 'dropdown',
            placeholder: 'Select tenure',
            options: [
              '12 Months',
              '24 Months',
              '36 Months',
              '48 Months',
              '60 Months',
              '72 Months',
              '120 Months',
              '180 Months',
              '240 Months',
              '300 Months',
            ],
            required: true,
            width: 'half',
          },
          {
            name: 'purposeOfFinance',
            label: 'Purpose of Finance',
            type: 'dropdown',
            placeholder: 'Select purpose',
            options: [
              'Residential Property Purchase',
              'Buy to Let',
              'Refinance',
              'Home Improvement',
              'Other',
            ],
            required: true,
            width: 'half',
          },
          {
            name: 'preferredMonthlyInstalmentDate',
            label: 'Preferred Monthly Instalment Date',
            type: 'dropdown',
            placeholder: 'Select date',
            options: [
              '1st of Every Month',
              '5th of Every Month',
              '10th of Every Month',
              '15th of Every Month',
              '20th of Every Month',
              '25th of Every Month',
            ],
            required: true,
            width: 'half',
          },
        ],
      },
      {
        title: 'Your Financial Commitments',
        fields: [
          {
            name: 'monthlyExpenses',
            label: 'Your Monthly Expenses',
            type: 'text',
            placeholder: '£0.00',
            required: true,
            width: 'half',
          },
          {
            name: 'preferredRepaymentAmount',
            label: 'Your preferred Repayment Amount',
            type: 'text',
            placeholder: '£0.00',
            required: true,
            width: 'half',
            helperText: 'Within Acceptable Limit',
          },
        ],
      },
    ],
  },

  {
    sectionTitle: '4. Bank Account Details & Documents Upload',
    groups: [
      {
        fields: [
          {
            name: 'accountHolderName',
            label: 'Account Holder Name',
            type: 'text',
            required: true,
            width: 'half',
          },
          {
            name: 'bankName',
            label: 'Bank Name',
            type: 'text',
            required: true,
            width: 'half',
          },
          {
            name: 'sortCode',
            label: 'Sort Code',
            type: 'text',
            required: true,
            width: 'half',
          },
          {
            name: 'accountNumber',
            label: 'Account Number',
            type: 'text',
            required: true,
            width: 'half',
          },
          {
            name: 'autoDebit',
            label: 'Auto Debit',
            type: 'dropdown',
            options: ['Enabled', 'Disabled'],
            required: true,
            width: 'half',
          },
        ],
      },

      {
        title:
          'Documents Uploaded (File Size should not exceed 2MB.,.Jpeg, .Pdf files only allowed)',
        fields: [
          {
            name: 'proofOfAddress',
            label: 'Proof of Address',
            type: 'file',
            width: 'half',
          },
          {
            name: 'bankStatements',
            label: 'Last 3 Months Bank Statements',
            type: 'file',
            width: 'half',
          },
          {
            name: 'payslips',
            label: 'Last 3 Payslips',
            type: 'file',
            width: 'half',
          },
          {
            name: 'propertyAgreement',
            label: 'Property Agreement',
            type: 'file',
            width: 'half',
          },
        ],
      },

      {
        title: 'Declaration',
        fields: [
          {
            name: 'declaration1',
            label: 'I confirm the information provided is accurate and complete.',
            type: 'checkbox',
            width: 'full',
          },
          {
            name: 'declaration2',
            label: 'I understand this finance follows Shariah principles.',
            type: 'checkbox',
            width: 'full',
          },
        ],
      },
    ],
  },
];
